{
  "name" : "Continuous Integration",
  "on" : {
    "push" : {
      "paths" : [
        "**.c",
        "**.h",
        "**.cpp",
        "**.hpp",
        "**.build",
        "**.in",
        "**.yml",
        "CMakeLists.txt",
        "Makefile"
      ]
    },
    "pull_request" : {
      "paths" : [
        "**.c",
        "**.h",
        "**.cpp",
        "**.hpp",
        "**.build",
        "**.in",
        "**.yml",
        "CMakeLists.txt",
        "Makefile"
      ]
    }
  },
  "jobs" : {
    "build-win32-native" : {
      "runs-on" : "windows-latest",
      "strategy" : {
        "matrix" : {
          "platform" : [
            {
              "vcpkg-target-triplet" : "x86-windows-static",
              "target-arch" : "intel32",
              "target-arch-msbuild" : "Win32",
              "executable-name" : "tvpwin32.exe",
              "compiler" : "msvc"
            },
            {
              "vcpkg-target-triplet" : "x64-windows-static",
              "target-arch" : "intel64",
              "target-arch-msbuild" : "x64",
              "executable-name" : "tvpwin64.exe",
              "compiler" : "msvc"
            }
          ]
        }
      },
      "timeout-minutes" : 30,
      "steps" : [
        {
          "name" : "Checkout repository",
          "uses" : "actions/checkout@v2",
          "with" : {
            "submodules" : "recursive"
          }
        },
        {
          "name" : "Set up NASM",
          "uses" : "ilammy/setup-nasm@v1",
          "with" : {
            "version" : "2.14.03rc2"
          }
        },
        {
          "name" : "Cache vcpkg binaries",
          "uses" : "actions/cache@v3",
          "with" : {
            "path" : "~/AppData/Local/vcpkg",
            "key" : "${{ runner.os }}-${{ matrix.platform.target-arch }}-${{ matrix.platform.compiler }}-vcpkg-cache"
          }
        },
        {
          "name" : "Configure project",
          "run" : "cmake -DCMAKE_GENERATOR_PLATFORM=${{ matrix.platform.target-arch-msbuild }} -DVCPKG_TARGET_TRIPLET=${{ matrix.platform.vcpkg-target-triplet }} -DVCPKG_CRT_LINKAGE=static -S . -B build-cmake"
        },
        {
          "name" : "Build project",
          "run" : "cmake --build build-cmake --config Release"
        },
        {
          "name" : "Upload artifact",
          "uses" : "actions/upload-artifact@master",
          "with" : {
            "name" : "binary-win32-${{ matrix.platform.target-arch }}-${{ matrix.platform.compiler }}",
            "path" : "build-cmake/Release/${{ matrix.platform.executable-name }}"
          }
        }
      ]
    }
  }
}
